header:
  seq: 0
  stamp:
    secs: 0
    nsecs: 0
  frame_id: ''
joint_names: ['joint_1', 'joint_2', 'joint_3', 'joint_4', 'joint_5', 'joint_6']
points:
  - positions: [1，2，3，4，5]
    velocities: []
    accelerations: []
    effort: []
    time_from_start: {secs: 1, nsecs: 0}
