// Generated by gencpp from file duco_msgs/DucoRobotStates.msg
// DO NOT EDIT!


#ifndef DUCO_MSGS_MESSAGE_DUCOROBOTSTATES_H
#define DUCO_MSGS_MESSAGE_DUCOROBOTSTATES_H

#include <ros/service_traits.h>


#include <duco_msgs/DucoRobotStatesRequest.h>
#include <duco_msgs/DucoRobotStatesResponse.h>


namespace duco_msgs
{

struct DucoRobotStates
{

typedef DucoRobotStatesRequest Request;
typedef DucoRobotStatesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DucoRobotStates
} // namespace duco_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::duco_msgs::DucoRobotStates > {
  static const char* value()
  {
    return "7b889afd34d7cc1017eae13c8627bb97";
  }

  static const char* value(const ::duco_msgs::DucoRobotStates&) { return value(); }
};

template<>
struct DataType< ::duco_msgs::DucoRobotStates > {
  static const char* value()
  {
    return "duco_msgs/DucoRobotStates";
  }

  static const char* value(const ::duco_msgs::DucoRobotStates&) { return value(); }
};


// service_traits::MD5Sum< ::duco_msgs::DucoRobotStatesRequest> should match
// service_traits::MD5Sum< ::duco_msgs::DucoRobotStates >
template<>
struct MD5Sum< ::duco_msgs::DucoRobotStatesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::duco_msgs::DucoRobotStates >::value();
  }
  static const char* value(const ::duco_msgs::DucoRobotStatesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::duco_msgs::DucoRobotStatesRequest> should match
// service_traits::DataType< ::duco_msgs::DucoRobotStates >
template<>
struct DataType< ::duco_msgs::DucoRobotStatesRequest>
{
  static const char* value()
  {
    return DataType< ::duco_msgs::DucoRobotStates >::value();
  }
  static const char* value(const ::duco_msgs::DucoRobotStatesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::duco_msgs::DucoRobotStatesResponse> should match
// service_traits::MD5Sum< ::duco_msgs::DucoRobotStates >
template<>
struct MD5Sum< ::duco_msgs::DucoRobotStatesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::duco_msgs::DucoRobotStates >::value();
  }
  static const char* value(const ::duco_msgs::DucoRobotStatesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::duco_msgs::DucoRobotStatesResponse> should match
// service_traits::DataType< ::duco_msgs::DucoRobotStates >
template<>
struct DataType< ::duco_msgs::DucoRobotStatesResponse>
{
  static const char* value()
  {
    return DataType< ::duco_msgs::DucoRobotStates >::value();
  }
  static const char* value(const ::duco_msgs::DucoRobotStatesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DUCO_MSGS_MESSAGE_DUCOROBOTSTATES_H
