// Generated by gencpp from file duco_msgs/DucoDigital.msg
// DO NOT EDIT!


#ifndef DUCO_MSGS_MESSAGE_DUCODIGITAL_H
#define DUCO_MSGS_MESSAGE_DUCODIGITAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace duco_msgs
{
template <class ContainerAllocator>
struct DucoDigital_
{
  typedef DucoDigital_<ContainerAllocator> Type;

  DucoDigital_()
    : pin(0)
    , flag(false)
    , state(false)  {
    }
  DucoDigital_(const ContainerAllocator& _alloc)
    : pin(0)
    , flag(false)
    , state(false)  {
  (void)_alloc;
    }



   typedef uint8_t _pin_type;
  _pin_type pin;

   typedef uint8_t _flag_type;
  _flag_type flag;

   typedef uint8_t _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::duco_msgs::DucoDigital_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::duco_msgs::DucoDigital_<ContainerAllocator> const> ConstPtr;

}; // struct DucoDigital_

typedef ::duco_msgs::DucoDigital_<std::allocator<void> > DucoDigital;

typedef boost::shared_ptr< ::duco_msgs::DucoDigital > DucoDigitalPtr;
typedef boost::shared_ptr< ::duco_msgs::DucoDigital const> DucoDigitalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::duco_msgs::DucoDigital_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::duco_msgs::DucoDigital_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::duco_msgs::DucoDigital_<ContainerAllocator1> & lhs, const ::duco_msgs::DucoDigital_<ContainerAllocator2> & rhs)
{
  return lhs.pin == rhs.pin &&
    lhs.flag == rhs.flag &&
    lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::duco_msgs::DucoDigital_<ContainerAllocator1> & lhs, const ::duco_msgs::DucoDigital_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace duco_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::duco_msgs::DucoDigital_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::duco_msgs::DucoDigital_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duco_msgs::DucoDigital_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duco_msgs::DucoDigital_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duco_msgs::DucoDigital_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duco_msgs::DucoDigital_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::duco_msgs::DucoDigital_<ContainerAllocator> >
{
  static const char* value()
  {
    return "27fea16c33a8e446fcacfee31d199a86";
  }

  static const char* value(const ::duco_msgs::DucoDigital_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x27fea16c33a8e446ULL;
  static const uint64_t static_value2 = 0xfcacfee31d199a86ULL;
};

template<class ContainerAllocator>
struct DataType< ::duco_msgs::DucoDigital_<ContainerAllocator> >
{
  static const char* value()
  {
    return "duco_msgs/DucoDigital";
  }

  static const char* value(const ::duco_msgs::DucoDigital_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::duco_msgs::DucoDigital_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 pin\n"
"bool flag\n"
"bool state\n"
;
  }

  static const char* value(const ::duco_msgs::DucoDigital_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::duco_msgs::DucoDigital_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pin);
      stream.next(m.flag);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DucoDigital_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::duco_msgs::DucoDigital_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::duco_msgs::DucoDigital_<ContainerAllocator>& v)
  {
    s << indent << "pin: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.pin);
    s << indent << "flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.flag);
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DUCO_MSGS_MESSAGE_DUCODIGITAL_H
