// Generated by gencpp from file duco_msgs/DucoGetFK.msg
// DO NOT EDIT!


#ifndef DUCO_MSGS_MESSAGE_DUCOGETFK_H
#define DUCO_MSGS_MESSAGE_DUCOGETFK_H

#include <ros/service_traits.h>


#include <duco_msgs/DucoGetFKRequest.h>
#include <duco_msgs/DucoGetFKResponse.h>


namespace duco_msgs
{

struct DucoGetFK
{

typedef DucoGetFKRequest Request;
typedef DucoGetFKResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DucoGetFK
} // namespace duco_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::duco_msgs::DucoGetFK > {
  static const char* value()
  {
    return "2c07157d0fbbe168e2662645c6ac7844";
  }

  static const char* value(const ::duco_msgs::DucoGetFK&) { return value(); }
};

template<>
struct DataType< ::duco_msgs::DucoGetFK > {
  static const char* value()
  {
    return "duco_msgs/DucoGetFK";
  }

  static const char* value(const ::duco_msgs::DucoGetFK&) { return value(); }
};


// service_traits::MD5Sum< ::duco_msgs::DucoGetFKRequest> should match
// service_traits::MD5Sum< ::duco_msgs::DucoGetFK >
template<>
struct MD5Sum< ::duco_msgs::DucoGetFKRequest>
{
  static const char* value()
  {
    return MD5Sum< ::duco_msgs::DucoGetFK >::value();
  }
  static const char* value(const ::duco_msgs::DucoGetFKRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::duco_msgs::DucoGetFKRequest> should match
// service_traits::DataType< ::duco_msgs::DucoGetFK >
template<>
struct DataType< ::duco_msgs::DucoGetFKRequest>
{
  static const char* value()
  {
    return DataType< ::duco_msgs::DucoGetFK >::value();
  }
  static const char* value(const ::duco_msgs::DucoGetFKRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::duco_msgs::DucoGetFKResponse> should match
// service_traits::MD5Sum< ::duco_msgs::DucoGetFK >
template<>
struct MD5Sum< ::duco_msgs::DucoGetFKResponse>
{
  static const char* value()
  {
    return MD5Sum< ::duco_msgs::DucoGetFK >::value();
  }
  static const char* value(const ::duco_msgs::DucoGetFKResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::duco_msgs::DucoGetFKResponse> should match
// service_traits::DataType< ::duco_msgs::DucoGetFK >
template<>
struct DataType< ::duco_msgs::DucoGetFKResponse>
{
  static const char* value()
  {
    return DataType< ::duco_msgs::DucoGetFK >::value();
  }
  static const char* value(const ::duco_msgs::DucoGetFKResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DUCO_MSGS_MESSAGE_DUCOGETFK_H
