// Generated by gencpp from file duco_msgs/DucoCommand.msg
// DO NOT EDIT!


#ifndef DUCO_MSGS_MESSAGE_DUCOCOMMAND_H
#define DUCO_MSGS_MESSAGE_DUCOCOMMAND_H

#include <ros/service_traits.h>


#include <duco_msgs/DucoCommandRequest.h>
#include <duco_msgs/DucoCommandResponse.h>


namespace duco_msgs
{

struct DucoCommand
{

typedef DucoCommandRequest Request;
typedef DucoCommandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DucoCommand
} // namespace duco_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::duco_msgs::DucoCommand > {
  static const char* value()
  {
    return "8413a3d40877c7c622b23a57cfe681a7";
  }

  static const char* value(const ::duco_msgs::DucoCommand&) { return value(); }
};

template<>
struct DataType< ::duco_msgs::DucoCommand > {
  static const char* value()
  {
    return "duco_msgs/DucoCommand";
  }

  static const char* value(const ::duco_msgs::DucoCommand&) { return value(); }
};


// service_traits::MD5Sum< ::duco_msgs::DucoCommandRequest> should match
// service_traits::MD5Sum< ::duco_msgs::DucoCommand >
template<>
struct MD5Sum< ::duco_msgs::DucoCommandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::duco_msgs::DucoCommand >::value();
  }
  static const char* value(const ::duco_msgs::DucoCommandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::duco_msgs::DucoCommandRequest> should match
// service_traits::DataType< ::duco_msgs::DucoCommand >
template<>
struct DataType< ::duco_msgs::DucoCommandRequest>
{
  static const char* value()
  {
    return DataType< ::duco_msgs::DucoCommand >::value();
  }
  static const char* value(const ::duco_msgs::DucoCommandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::duco_msgs::DucoCommandResponse> should match
// service_traits::MD5Sum< ::duco_msgs::DucoCommand >
template<>
struct MD5Sum< ::duco_msgs::DucoCommandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::duco_msgs::DucoCommand >::value();
  }
  static const char* value(const ::duco_msgs::DucoCommandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::duco_msgs::DucoCommandResponse> should match
// service_traits::DataType< ::duco_msgs::DucoCommand >
template<>
struct DataType< ::duco_msgs::DucoCommandResponse>
{
  static const char* value()
  {
    return DataType< ::duco_msgs::DucoCommand >::value();
  }
  static const char* value(const ::duco_msgs::DucoCommandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DUCO_MSGS_MESSAGE_DUCOCOMMAND_H
