// Generated by gencpp from file duco_msgs/DucoIOStates.msg
// DO NOT EDIT!


#ifndef DUCO_MSGS_MESSAGE_DUCOIOSTATES_H
#define DUCO_MSGS_MESSAGE_DUCOIOSTATES_H

#include <ros/service_traits.h>


#include <duco_msgs/DucoIOStatesRequest.h>
#include <duco_msgs/DucoIOStatesResponse.h>


namespace duco_msgs
{

struct DucoIOStates
{

typedef DucoIOStatesRequest Request;
typedef DucoIOStatesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DucoIOStates
} // namespace duco_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::duco_msgs::DucoIOStates > {
  static const char* value()
  {
    return "d73a38548e6ecc94c1d3393d8cbc66ab";
  }

  static const char* value(const ::duco_msgs::DucoIOStates&) { return value(); }
};

template<>
struct DataType< ::duco_msgs::DucoIOStates > {
  static const char* value()
  {
    return "duco_msgs/DucoIOStates";
  }

  static const char* value(const ::duco_msgs::DucoIOStates&) { return value(); }
};


// service_traits::MD5Sum< ::duco_msgs::DucoIOStatesRequest> should match
// service_traits::MD5Sum< ::duco_msgs::DucoIOStates >
template<>
struct MD5Sum< ::duco_msgs::DucoIOStatesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::duco_msgs::DucoIOStates >::value();
  }
  static const char* value(const ::duco_msgs::DucoIOStatesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::duco_msgs::DucoIOStatesRequest> should match
// service_traits::DataType< ::duco_msgs::DucoIOStates >
template<>
struct DataType< ::duco_msgs::DucoIOStatesRequest>
{
  static const char* value()
  {
    return DataType< ::duco_msgs::DucoIOStates >::value();
  }
  static const char* value(const ::duco_msgs::DucoIOStatesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::duco_msgs::DucoIOStatesResponse> should match
// service_traits::MD5Sum< ::duco_msgs::DucoIOStates >
template<>
struct MD5Sum< ::duco_msgs::DucoIOStatesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::duco_msgs::DucoIOStates >::value();
  }
  static const char* value(const ::duco_msgs::DucoIOStatesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::duco_msgs::DucoIOStatesResponse> should match
// service_traits::DataType< ::duco_msgs::DucoIOStates >
template<>
struct DataType< ::duco_msgs::DucoIOStatesResponse>
{
  static const char* value()
  {
    return DataType< ::duco_msgs::DucoIOStates >::value();
  }
  static const char* value(const ::duco_msgs::DucoIOStatesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DUCO_MSGS_MESSAGE_DUCOIOSTATES_H
