// Generated by gencpp from file duco_msgs/DucoAnalog.msg
// DO NOT EDIT!


#ifndef DUCO_MSGS_MESSAGE_DUCOANALOG_H
#define DUCO_MSGS_MESSAGE_DUCOANALOG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace duco_msgs
{
template <class ContainerAllocator>
struct DucoAnalog_
{
  typedef DucoAnalog_<ContainerAllocator> Type;

  DucoAnalog_()
    : pin(0)
    , state(0.0)  {
    }
  DucoAnalog_(const ContainerAllocator& _alloc)
    : pin(0)
    , state(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _pin_type;
  _pin_type pin;

   typedef double _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::duco_msgs::DucoAnalog_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::duco_msgs::DucoAnalog_<ContainerAllocator> const> ConstPtr;

}; // struct DucoAnalog_

typedef ::duco_msgs::DucoAnalog_<std::allocator<void> > DucoAnalog;

typedef boost::shared_ptr< ::duco_msgs::DucoAnalog > DucoAnalogPtr;
typedef boost::shared_ptr< ::duco_msgs::DucoAnalog const> DucoAnalogConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::duco_msgs::DucoAnalog_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::duco_msgs::DucoAnalog_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::duco_msgs::DucoAnalog_<ContainerAllocator1> & lhs, const ::duco_msgs::DucoAnalog_<ContainerAllocator2> & rhs)
{
  return lhs.pin == rhs.pin &&
    lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::duco_msgs::DucoAnalog_<ContainerAllocator1> & lhs, const ::duco_msgs::DucoAnalog_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace duco_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::duco_msgs::DucoAnalog_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::duco_msgs::DucoAnalog_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duco_msgs::DucoAnalog_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duco_msgs::DucoAnalog_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duco_msgs::DucoAnalog_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duco_msgs::DucoAnalog_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::duco_msgs::DucoAnalog_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c4fdd0f2fe59ae5f40617c11fc52844a";
  }

  static const char* value(const ::duco_msgs::DucoAnalog_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc4fdd0f2fe59ae5fULL;
  static const uint64_t static_value2 = 0x40617c11fc52844aULL;
};

template<class ContainerAllocator>
struct DataType< ::duco_msgs::DucoAnalog_<ContainerAllocator> >
{
  static const char* value()
  {
    return "duco_msgs/DucoAnalog";
  }

  static const char* value(const ::duco_msgs::DucoAnalog_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::duco_msgs::DucoAnalog_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 pin\n"
"float64 state\n"
;
  }

  static const char* value(const ::duco_msgs::DucoAnalog_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::duco_msgs::DucoAnalog_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pin);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DucoAnalog_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::duco_msgs::DucoAnalog_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::duco_msgs::DucoAnalog_<ContainerAllocator>& v)
  {
    s << indent << "pin: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.pin);
    s << indent << "state: ";
    Printer<double>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DUCO_MSGS_MESSAGE_DUCOANALOG_H
