// Generated by gencpp from file duco_msgs/DucoGetIKResponse.msg
// DO NOT EDIT!


#ifndef DUCO_MSGS_MESSAGE_DUCOGETIKRESPONSE_H
#define DUCO_MSGS_MESSAGE_DUCOGETIKRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace duco_msgs
{
template <class ContainerAllocator>
struct DucoGetIKResponse_
{
  typedef DucoGetIKResponse_<ContainerAllocator> Type;

  DucoGetIKResponse_()
    : joint()
    , success(false)  {
    }
  DucoGetIKResponse_(const ContainerAllocator& _alloc)
    : joint(_alloc)
    , success(false)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _joint_type;
  _joint_type joint;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::duco_msgs::DucoGetIKResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::duco_msgs::DucoGetIKResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DucoGetIKResponse_

typedef ::duco_msgs::DucoGetIKResponse_<std::allocator<void> > DucoGetIKResponse;

typedef boost::shared_ptr< ::duco_msgs::DucoGetIKResponse > DucoGetIKResponsePtr;
typedef boost::shared_ptr< ::duco_msgs::DucoGetIKResponse const> DucoGetIKResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::duco_msgs::DucoGetIKResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::duco_msgs::DucoGetIKResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::duco_msgs::DucoGetIKResponse_<ContainerAllocator1> & lhs, const ::duco_msgs::DucoGetIKResponse_<ContainerAllocator2> & rhs)
{
  return lhs.joint == rhs.joint &&
    lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::duco_msgs::DucoGetIKResponse_<ContainerAllocator1> & lhs, const ::duco_msgs::DucoGetIKResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace duco_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::duco_msgs::DucoGetIKResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::duco_msgs::DucoGetIKResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duco_msgs::DucoGetIKResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duco_msgs::DucoGetIKResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duco_msgs::DucoGetIKResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duco_msgs::DucoGetIKResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::duco_msgs::DucoGetIKResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "83f900751b71a68c79ce570ca0d2e109";
  }

  static const char* value(const ::duco_msgs::DucoGetIKResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x83f900751b71a68cULL;
  static const uint64_t static_value2 = 0x79ce570ca0d2e109ULL;
};

template<class ContainerAllocator>
struct DataType< ::duco_msgs::DucoGetIKResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "duco_msgs/DucoGetIKResponse";
  }

  static const char* value(const ::duco_msgs::DucoGetIKResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::duco_msgs::DucoGetIKResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] joint\n"
"bool success\n"
"\n"
;
  }

  static const char* value(const ::duco_msgs::DucoGetIKResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::duco_msgs::DucoGetIKResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DucoGetIKResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::duco_msgs::DucoGetIKResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::duco_msgs::DucoGetIKResponse_<ContainerAllocator>& v)
  {
    s << indent << "joint[]" << std::endl;
    for (size_t i = 0; i < v.joint.size(); ++i)
    {
      s << indent << "  joint[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.joint[i]);
    }
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DUCO_MSGS_MESSAGE_DUCOGETIKRESPONSE_H
