// Generated by gencpp from file duco_msgs/DucoRobotStatesRequest.msg
// DO NOT EDIT!


#ifndef DUCO_MSGS_MESSAGE_DUCOROBOTSTATESREQUEST_H
#define DUCO_MSGS_MESSAGE_DUCOROBOTSTATESREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace duco_msgs
{
template <class ContainerAllocator>
struct DucoRobotStatesRequest_
{
  typedef DucoRobotStatesRequest_<ContainerAllocator> Type;

  DucoRobotStatesRequest_()
    {
    }
  DucoRobotStatesRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::duco_msgs::DucoRobotStatesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::duco_msgs::DucoRobotStatesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DucoRobotStatesRequest_

typedef ::duco_msgs::DucoRobotStatesRequest_<std::allocator<void> > DucoRobotStatesRequest;

typedef boost::shared_ptr< ::duco_msgs::DucoRobotStatesRequest > DucoRobotStatesRequestPtr;
typedef boost::shared_ptr< ::duco_msgs::DucoRobotStatesRequest const> DucoRobotStatesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::duco_msgs::DucoRobotStatesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::duco_msgs::DucoRobotStatesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace duco_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::duco_msgs::DucoRobotStatesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::duco_msgs::DucoRobotStatesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duco_msgs::DucoRobotStatesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duco_msgs::DucoRobotStatesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duco_msgs::DucoRobotStatesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duco_msgs::DucoRobotStatesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::duco_msgs::DucoRobotStatesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::duco_msgs::DucoRobotStatesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::duco_msgs::DucoRobotStatesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "duco_msgs/DucoRobotStatesRequest";
  }

  static const char* value(const ::duco_msgs::DucoRobotStatesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::duco_msgs::DucoRobotStatesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::duco_msgs::DucoRobotStatesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::duco_msgs::DucoRobotStatesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DucoRobotStatesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::duco_msgs::DucoRobotStatesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::duco_msgs::DucoRobotStatesRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // DUCO_MSGS_MESSAGE_DUCOROBOTSTATESREQUEST_H
