// Generated by gencpp from file duco_msgs/DucoGetIKRequest.msg
// DO NOT EDIT!


#ifndef DUCO_MSGS_MESSAGE_DUCOGETIKREQUEST_H
#define DUCO_MSGS_MESSAGE_DUCOGETIKREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace duco_msgs
{
template <class ContainerAllocator>
struct DucoGetIKRequest_
{
  typedef DucoGetIKRequest_<ContainerAllocator> Type;

  DucoGetIKRequest_()
    : ref_joint()
    , pos()
    , rpy()  {
    }
  DucoGetIKRequest_(const ContainerAllocator& _alloc)
    : ref_joint(_alloc)
    , pos(_alloc)
    , rpy(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _ref_joint_type;
  _ref_joint_type ref_joint;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _pos_type;
  _pos_type pos;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _rpy_type;
  _rpy_type rpy;





  typedef boost::shared_ptr< ::duco_msgs::DucoGetIKRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::duco_msgs::DucoGetIKRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DucoGetIKRequest_

typedef ::duco_msgs::DucoGetIKRequest_<std::allocator<void> > DucoGetIKRequest;

typedef boost::shared_ptr< ::duco_msgs::DucoGetIKRequest > DucoGetIKRequestPtr;
typedef boost::shared_ptr< ::duco_msgs::DucoGetIKRequest const> DucoGetIKRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::duco_msgs::DucoGetIKRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::duco_msgs::DucoGetIKRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::duco_msgs::DucoGetIKRequest_<ContainerAllocator1> & lhs, const ::duco_msgs::DucoGetIKRequest_<ContainerAllocator2> & rhs)
{
  return lhs.ref_joint == rhs.ref_joint &&
    lhs.pos == rhs.pos &&
    lhs.rpy == rhs.rpy;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::duco_msgs::DucoGetIKRequest_<ContainerAllocator1> & lhs, const ::duco_msgs::DucoGetIKRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace duco_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::duco_msgs::DucoGetIKRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::duco_msgs::DucoGetIKRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duco_msgs::DucoGetIKRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duco_msgs::DucoGetIKRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duco_msgs::DucoGetIKRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duco_msgs::DucoGetIKRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::duco_msgs::DucoGetIKRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "558f1d9d17046e2e1df9c03f2d2b2cb9";
  }

  static const char* value(const ::duco_msgs::DucoGetIKRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x558f1d9d17046e2eULL;
  static const uint64_t static_value2 = 0x1df9c03f2d2b2cb9ULL;
};

template<class ContainerAllocator>
struct DataType< ::duco_msgs::DucoGetIKRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "duco_msgs/DucoGetIKRequest";
  }

  static const char* value(const ::duco_msgs::DucoGetIKRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::duco_msgs::DucoGetIKRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] ref_joint\n"
"float32[] pos\n"
"float32[] rpy\n"
;
  }

  static const char* value(const ::duco_msgs::DucoGetIKRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::duco_msgs::DucoGetIKRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ref_joint);
      stream.next(m.pos);
      stream.next(m.rpy);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DucoGetIKRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::duco_msgs::DucoGetIKRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::duco_msgs::DucoGetIKRequest_<ContainerAllocator>& v)
  {
    s << indent << "ref_joint[]" << std::endl;
    for (size_t i = 0; i < v.ref_joint.size(); ++i)
    {
      s << indent << "  ref_joint[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.ref_joint[i]);
    }
    s << indent << "pos[]" << std::endl;
    for (size_t i = 0; i < v.pos.size(); ++i)
    {
      s << indent << "  pos[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.pos[i]);
    }
    s << indent << "rpy[]" << std::endl;
    for (size_t i = 0; i < v.rpy.size(); ++i)
    {
      s << indent << "  rpy[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.rpy[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DUCO_MSGS_MESSAGE_DUCOGETIKREQUEST_H
