// Generated by gencpp from file duco_msgs/DucoCommandResponse.msg
// DO NOT EDIT!


#ifndef DUCO_MSGS_MESSAGE_DUCOCOMMANDRESPONSE_H
#define DUCO_MSGS_MESSAGE_DUCOCOMMANDRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace duco_msgs
{
template <class ContainerAllocator>
struct DucoCommandResponse_
{
  typedef DucoCommandResponse_<ContainerAllocator> Type;

  DucoCommandResponse_()
    : state(0)  {
    }
  DucoCommandResponse_(const ContainerAllocator& _alloc)
    : state(0)  {
  (void)_alloc;
    }



   typedef int32_t _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::duco_msgs::DucoCommandResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::duco_msgs::DucoCommandResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DucoCommandResponse_

typedef ::duco_msgs::DucoCommandResponse_<std::allocator<void> > DucoCommandResponse;

typedef boost::shared_ptr< ::duco_msgs::DucoCommandResponse > DucoCommandResponsePtr;
typedef boost::shared_ptr< ::duco_msgs::DucoCommandResponse const> DucoCommandResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::duco_msgs::DucoCommandResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::duco_msgs::DucoCommandResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::duco_msgs::DucoCommandResponse_<ContainerAllocator1> & lhs, const ::duco_msgs::DucoCommandResponse_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::duco_msgs::DucoCommandResponse_<ContainerAllocator1> & lhs, const ::duco_msgs::DucoCommandResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace duco_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::duco_msgs::DucoCommandResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::duco_msgs::DucoCommandResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duco_msgs::DucoCommandResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duco_msgs::DucoCommandResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duco_msgs::DucoCommandResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duco_msgs::DucoCommandResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::duco_msgs::DucoCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7a2f37ef2ba405f0c7a15cc72663d6f0";
  }

  static const char* value(const ::duco_msgs::DucoCommandResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7a2f37ef2ba405f0ULL;
  static const uint64_t static_value2 = 0xc7a15cc72663d6f0ULL;
};

template<class ContainerAllocator>
struct DataType< ::duco_msgs::DucoCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "duco_msgs/DucoCommandResponse";
  }

  static const char* value(const ::duco_msgs::DucoCommandResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::duco_msgs::DucoCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#true:finish false:error\n"
"int32 state\n"
"\n"
;
  }

  static const char* value(const ::duco_msgs::DucoCommandResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::duco_msgs::DucoCommandResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DucoCommandResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::duco_msgs::DucoCommandResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::duco_msgs::DucoCommandResponse_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<int32_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DUCO_MSGS_MESSAGE_DUCOCOMMANDRESPONSE_H
