// Generated by gencpp from file duco_msgs/DucoGetIK.msg
// DO NOT EDIT!


#ifndef DUCO_MSGS_MESSAGE_DUCOGETIK_H
#define DUCO_MSGS_MESSAGE_DUCOGETIK_H

#include <ros/service_traits.h>


#include <duco_msgs/DucoGetIKRequest.h>
#include <duco_msgs/DucoGetIKResponse.h>


namespace duco_msgs
{

struct DucoGetIK
{

typedef DucoGetIKRequest Request;
typedef DucoGetIKResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DucoGetIK
} // namespace duco_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::duco_msgs::DucoGetIK > {
  static const char* value()
  {
    return "733c3eca96e1291b2ee883e81a04df06";
  }

  static const char* value(const ::duco_msgs::DucoGetIK&) { return value(); }
};

template<>
struct DataType< ::duco_msgs::DucoGetIK > {
  static const char* value()
  {
    return "duco_msgs/DucoGetIK";
  }

  static const char* value(const ::duco_msgs::DucoGetIK&) { return value(); }
};


// service_traits::MD5Sum< ::duco_msgs::DucoGetIKRequest> should match
// service_traits::MD5Sum< ::duco_msgs::DucoGetIK >
template<>
struct MD5Sum< ::duco_msgs::DucoGetIKRequest>
{
  static const char* value()
  {
    return MD5Sum< ::duco_msgs::DucoGetIK >::value();
  }
  static const char* value(const ::duco_msgs::DucoGetIKRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::duco_msgs::DucoGetIKRequest> should match
// service_traits::DataType< ::duco_msgs::DucoGetIK >
template<>
struct DataType< ::duco_msgs::DucoGetIKRequest>
{
  static const char* value()
  {
    return DataType< ::duco_msgs::DucoGetIK >::value();
  }
  static const char* value(const ::duco_msgs::DucoGetIKRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::duco_msgs::DucoGetIKResponse> should match
// service_traits::MD5Sum< ::duco_msgs::DucoGetIK >
template<>
struct MD5Sum< ::duco_msgs::DucoGetIKResponse>
{
  static const char* value()
  {
    return MD5Sum< ::duco_msgs::DucoGetIK >::value();
  }
  static const char* value(const ::duco_msgs::DucoGetIKResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::duco_msgs::DucoGetIKResponse> should match
// service_traits::DataType< ::duco_msgs::DucoGetIK >
template<>
struct DataType< ::duco_msgs::DucoGetIKResponse>
{
  static const char* value()
  {
    return DataType< ::duco_msgs::DucoGetIK >::value();
  }
  static const char* value(const ::duco_msgs::DucoGetIKResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DUCO_MSGS_MESSAGE_DUCOGETIK_H
