// Generated by gencpp from file duco_msgs/DucoIOStatesResponse.msg
// DO NOT EDIT!


#ifndef DUCO_MSGS_MESSAGE_DUCOIOSTATESRESPONSE_H
#define DUCO_MSGS_MESSAGE_DUCOIOSTATESRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace duco_msgs
{
template <class ContainerAllocator>
struct DucoIOStatesResponse_
{
  typedef DucoIOStatesResponse_<ContainerAllocator> Type;

  DucoIOStatesResponse_()
    : result(false)  {
    }
  DucoIOStatesResponse_(const ContainerAllocator& _alloc)
    : result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::duco_msgs::DucoIOStatesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::duco_msgs::DucoIOStatesResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DucoIOStatesResponse_

typedef ::duco_msgs::DucoIOStatesResponse_<std::allocator<void> > DucoIOStatesResponse;

typedef boost::shared_ptr< ::duco_msgs::DucoIOStatesResponse > DucoIOStatesResponsePtr;
typedef boost::shared_ptr< ::duco_msgs::DucoIOStatesResponse const> DucoIOStatesResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::duco_msgs::DucoIOStatesResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::duco_msgs::DucoIOStatesResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::duco_msgs::DucoIOStatesResponse_<ContainerAllocator1> & lhs, const ::duco_msgs::DucoIOStatesResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::duco_msgs::DucoIOStatesResponse_<ContainerAllocator1> & lhs, const ::duco_msgs::DucoIOStatesResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace duco_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::duco_msgs::DucoIOStatesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::duco_msgs::DucoIOStatesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duco_msgs::DucoIOStatesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duco_msgs::DucoIOStatesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duco_msgs::DucoIOStatesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duco_msgs::DucoIOStatesResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::duco_msgs::DucoIOStatesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::duco_msgs::DucoIOStatesResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb13ac1f1354ccecULL;
  static const uint64_t static_value2 = 0xb7941ee8fa2192e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::duco_msgs::DucoIOStatesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "duco_msgs/DucoIOStatesResponse";
  }

  static const char* value(const ::duco_msgs::DucoIOStatesResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::duco_msgs::DucoIOStatesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#获取操作结果\n"
"bool result\n"
"\n"
"\n"
;
  }

  static const char* value(const ::duco_msgs::DucoIOStatesResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::duco_msgs::DucoIOStatesResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DucoIOStatesResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::duco_msgs::DucoIOStatesResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::duco_msgs::DucoIOStatesResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DUCO_MSGS_MESSAGE_DUCOIOSTATESRESPONSE_H
